DROP DATABASE IF EXISTS TIENDA_BIBLIOTECA_DB;
CREATE DATABASE TIENDA_BIBLIOTECA_DB
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;
USE TIENDA_BIBLIOTECA_DB;

-- Modulo 1: Accesos y Sucursales
CREATE TABLE ROL (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE 					VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION 			VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE SUCURSAL (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE 					VARCHAR(100) NOT NULL,
    DIRECCION 				VARCHAR(255) NOT NULL,
    TELEFONO 				VARCHAR(20),
    TIENE_BIBLIOTECA 		BOOLEAN DEFAULT FALSE,
    CREADO_EN 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE USUARIO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_COMPLETO 		VARCHAR(150) NOT NULL,
    EMAIL 					VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH 			VARCHAR(255) NOT NULL,
    ACTIVO 					BOOLEAN DEFAULT TRUE,
    CREADO_EN 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE USUARIO_ROL (
    USUARIO_ID 				INT NOT NULL,
    ROL_ID 					INT NOT NULL,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    CONSTRAINT FK_UR_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON DELETE CASCADE
) ENGINE=InnoDB;


-- Modulo 2: Catalago de productos
CREATE TABLE CATEGORIA (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE 					VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE EDITORIAL (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE 					VARCHAR(100) NOT NULL UNIQUE,
    PAIS 					VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE AUTOR (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE 					VARCHAR(150) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE LIBRO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    ISBN 					VARCHAR(20) NOT NULL UNIQUE,
    TITULO 					VARCHAR(255) NOT NULL,
    SLUG 					VARCHAR(255) UNIQUE,              -- URL amigable para el frontend web
    IMAGEN_PORTADA 			VARCHAR(255),            -- Ruta del archivo o URL de la imagen
    SINOPSIS 				TEXT,
    PAGINAS 				INT NOT NULL,
    FORMATO 				ENUM('TAPA_BLANDA', 'TAPA_DURA', 'DE_BOLSILLO') NOT NULL DEFAULT 'TAPA_BLANDA',
    PRECIO_VENTA_ACTUAL 	DECIMAL(10,2) NOT NULL,
    PRECIO_ALQUILER_ACTUAL 	DECIMAL(10,2) DEFAULT 0.00,
    EDITORIAL_ID 			INT NOT NULL,
    ACTIVO 					BOOLEAN DEFAULT TRUE,
    CREADO_EN 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT CHK_LIBRO_PAGINAS CHECK (PAGINAS > 0),
    CONSTRAINT CHK_LIBRO_PRECIO_VENTA CHECK (PRECIO_VENTA_ACTUAL >= 0),
    CONSTRAINT CHK_LIBRO_PRECIO_ALQUILER CHECK (PRECIO_ALQUILER_ACTUAL >= 0),
    CONSTRAINT FK_LIBRO_EDITORIAL FOREIGN KEY (EDITORIAL_ID) REFERENCES EDITORIAL(ID),
    
    INDEX IDX_LIBRO_TITULO (TITULO),
    INDEX IDX_LIBRO_ISBN (ISBN)
) ENGINE=InnoDB;

CREATE TABLE LIBRO_AUTOR (
    LIBRO_ID 				INT NOT NULL,
    AUTOR_ID 				INT NOT NULL,
    PRIMARY KEY (LIBRO_ID, AUTOR_ID),
    CONSTRAINT FK_LA_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LA_AUTOR FOREIGN KEY (AUTOR_ID) REFERENCES AUTOR(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE LIBRO_CATEGORIA (
    LIBRO_ID 				INT NOT NULL,
    CATEGORIA_ID 			INT NOT NULL,
    PRIMARY KEY (LIBRO_ID, CATEGORIA_ID),
    CONSTRAINT FK_LC_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LC_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Modulo 3: Clientes y Reseña
CREATE TABLE CLIENTE (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID 				INT UNIQUE NULL,             -- NULL si el cliente se registra por módulo B2B físico
    NOMBRE_RAZON_SOCIAL 	VARCHAR(150) NOT NULL,
    TIPO_CLIENTE 			ENUM('INDIVIDUAL', 'INSTITUCION') NOT NULL,
    TIPO_DOCUMENTO 			ENUM('DNI', 'RUC') NOT NULL,
    NUMERO_DOCUMENTO 		VARCHAR(20) NOT NULL UNIQUE,
    EMAIL_CONTACTO 			VARCHAR(100),
    TELEFONO 				VARCHAR(20),
    ACTIVO 					BOOLEAN DEFAULT TRUE,
    CREADO_EN 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT CHK_CLIENTE_DOCUMENTO CHECK (
        (TIPO_DOCUMENTO = 'DNI' AND LENGTH(NUMERO_DOCUMENTO)=8) OR
        (TIPO_DOCUMENTO = 'RUC' AND LENGTH(NUMERO_DOCUMENTO)=11)
    ),
    CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE DIRECCION_ENVIO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID 				INT NOT NULL,
    ETIQUETA 				VARCHAR(50) NOT NULL,          -- Ej: 'Casa', 'Trabajo', 'Sede Central'
    DIRECCION_COMPLETA 		VARCHAR(255) NOT NULL,
    CIUDAD 					VARCHAR(100) NOT NULL,
    CODIGO_POSTAL 			VARCHAR(20),
    CONSTRAINT FK_DIR_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE INSTITUCION (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID 				INT NOT NULL UNIQUE,
    TIPO_INSTITUCION 		ENUM('UNIVERSIDAD', 'COLEGIO', 'BIBLIOTECA', 'EMPRESA', 'OTRO') NOT NULL,
    PERSONA_CONTACTO 		VARCHAR(150),
    CONSTRAINT FK_INST_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CONTRATO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    INSTITUCION_ID 			INT NOT NULL,
    CODIGO_CONTRATO 		VARCHAR(50) NOT NULL UNIQUE,
    FECHA_INICIO 			DATE NOT NULL,
    FECHA_FIN 				DATE NOT NULL,
    DESCUENTO_PORCENTAJE 	DECIMAL(5,2) DEFAULT 0.00,
    ESTADO 					ENUM('ACTIVO', 'VENCIDO', 'CANCELADO') DEFAULT 'ACTIVO',
    
    CONSTRAINT CHK_CONTRATO_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT CHK_CONTRATO_DESCUENTO CHECK (DESCUENTO_PORCENTAJE >= 0 AND DESCUENTO_PORCENTAJE <= 100),
    CONSTRAINT FK_CONTRATO_INSTITUCION FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCION(ID)
) ENGINE=InnoDB;

CREATE TABLE COTIZACION (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    INSTITUCION_ID 			INT NOT NULL,
    USUARIO_VENDEDOR_ID 	INT NOT NULL,
    ESTADO 					ENUM('BORRADOR', 'ENVIADA', 'APROBADA', 'RECHAZADA', 'VENCIDA') DEFAULT 'BORRADOR',
    TOTAL_ESTIMADO 			DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    FECHA_EMISION 			DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_VALIDEZ 			DATETIME NOT NULL,
    
    CONSTRAINT FK_COTIZ_INSTITUCION FOREIGN KEY (INSTITUCION_ID) REFERENCES INSTITUCION(ID),
    CONSTRAINT FK_COTIZ_VENDEDOR FOREIGN KEY (USUARIO_VENDEDOR_ID) REFERENCES USUARIO(ID)
) ENGINE=InnoDB;

CREATE TABLE RESENA_LIBRO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    LIBRO_ID 				INT NOT NULL,
    CLIENTE_ID 				INT NOT NULL,
    CALIFICACION 			TINYINT NOT NULL CHECK (CALIFICACION BETWEEN 1 AND 5),
    COMENTARIO 				TEXT,
    APROBADO_MODERADOR 		BOOLEAN DEFAULT FALSE,
    FECHA_CREACION 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_RESENA_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESENA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Modulo 4: Logistica y Control de Stock
CREATE TABLE INVENTARIO_VENTA (
    SUCURSAL_ID 			INT NOT NULL,
    LIBRO_ID 				INT NOT NULL,
    CANTIDAD_DISPONIBLE 	INT NOT NULL DEFAULT 0,
    CANTIDAD_RESERVADA 		INT NOT NULL DEFAULT 0,
    STOCK_MINIMO 			INT DEFAULT 5,
    STOCK_MAXIMO 			INT DEFAULT 1000,
    PRIMARY KEY (SUCURSAL_ID, LIBRO_ID),
    
    CONSTRAINT CHK_INV_DISPONIBLE CHECK (CANTIDAD_DISPONIBLE >= 0),
    CONSTRAINT CHK_INV_RESERVADA CHECK (CANTIDAD_RESERVADA >= 0 AND CANTIDAD_RESERVADA <= CANTIDAD_DISPONIBLE),
    CONSTRAINT FK_INV_SUCURSAL FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID) ON DELETE CASCADE,
    CONSTRAINT FK_INV_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MOVIMIENTOS_INVENTARIO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID 				INT NULL,                    -- Operador que realiza el movimiento
    SUCURSAL_ID 			INT NOT NULL,
    LIBRO_ID 				INT NOT NULL,
	TIPO_MOVIMIENTO 		ENUM(
								'INGRESO_PROVEEDOR', 'VENTA_FISICA', 'VENTA_ONLINE', 
								'DEVOLUCION', 'MERMA', 'TRASLADO_ENTRADA', 
								'TRASLADO_SALIDA', 'AJUSTE_MANUAL', 'DESCARTE_BIBLIOTECA' -- Descarte añadido
								) NOT NULL,
    TIPO_REFERENCIA 		ENUM('PEDIDO', 'PRESTAMO', 'AJUSTE', 'TRASLADO', 'EJEMPLAR') NULL, -- Ejemplar añadido
    REFERENCIA_ID 			INT NULL,                 -- ID de la tabla referenciada arriba
    CANTIDAD 				INT NOT NULL,
    DESCRIPCION 			VARCHAR(255),
    FECHA_MOVIMIENTO 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT CHK_MOV_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT FK_MOV_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT FK_MOV_SUCURSAL FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID),
    CONSTRAINT FK_MOV_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID)
) ENGINE=InnoDB;

-- Modulo 5: Proceso de Ventas
CREATE TABLE CARRITO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID 				INT NOT NULL UNIQUE,
    CREADO_EN 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CARRITO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CARRITO_DETALLE (
    CARRITO_ID 				INT NOT NULL,
    LIBRO_ID 				INT NOT NULL,
    CANTIDAD 				INT NOT NULL DEFAULT 1,
    PRIMARY KEY (CARRITO_ID, LIBRO_ID),
    
    CONSTRAINT CHK_CARRITO_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT FK_CD_CARRITO FOREIGN KEY (CARRITO_ID) REFERENCES CARRITO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CD_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PEDIDO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID 				INT NOT NULL,
    SUCURSAL_ID 			INT NULL,
    USUARIO_VENDEDOR_ID 	INT NULL,
    CONTRATO_ID 			INT NULL,
    DIRECCION_ENVIO_ID 		INT NULL,
    CANAL_VENTA 			ENUM('FISICO', 'ONLINE') NOT NULL,
    TIPO_ENTREGA 			ENUM('RECOJO_TIENDA', 'DELIVERY') NOT NULL,
    ESTADO_ACTUAL 			ENUM('PENDIENTE_PAGO', 'PAGADO', 'PROCESANDO', 'ENVIADO', 'ENTREGADO', 'CANCELADO') DEFAULT 'PENDIENTE_PAGO',
    TOTAL 					DECIMAL(12,2) NOT NULL,
    FECHA_PEDIDO 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREADO_EN 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT CHK_PEDIDO_TOTAL CHECK (TOTAL >= 0),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_PEDIDO_SUCURSAL FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID),
    CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY (USUARIO_VENDEDOR_ID) REFERENCES USUARIO(ID),
    CONSTRAINT FK_PEDIDO_CONTRATO FOREIGN KEY (CONTRATO_ID) REFERENCES CONTRATO(ID),
    CONSTRAINT FK_PEDIDO_DIRECCION FOREIGN KEY (DIRECCION_ENVIO_ID) REFERENCES DIRECCION_ENVIO(ID)
) ENGINE=InnoDB;

CREATE TABLE DETALLE_PEDIDO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID 				INT NOT NULL,
    LIBRO_ID 				INT NOT NULL,
    CANTIDAD 				INT NOT NULL,
    PRECIO_UNITARIO 		DECIMAL(10,2) NOT NULL,
    SUBTOTAL 				DECIMAL(12,2) NOT NULL,
    
    CONSTRAINT UK_PEDIDO_LIBRO UNIQUE (PEDIDO_ID, LIBRO_ID),
    CONSTRAINT CHK_DP_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CHK_DP_PRECIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT CHK_DP_SUBTOTAL CHECK (SUBTOTAL >= 0),
    CONSTRAINT FK_DP_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DP_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID)
) ENGINE=InnoDB;

CREATE TABLE HISTORIAL_ESTADO_PEDIDO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID 				INT NOT NULL,
    USUARIO_ID 				INT NULL,
    ESTADO 					ENUM('PENDIENTE_PAGO', 'PAGADO', 'PROCESANDO', 'ENVIADO', 'ENTREGADO', 'CANCELADO') NOT NULL,
    NOTAS 					VARCHAR(255),
    FECHA_CAMBIO 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_HEP_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_HEP_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
) ENGINE=InnoDB;

CREATE TABLE PAGO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID 	  			INT NOT NULL,
    TIPO_TRANSACCION 		ENUM('PAGO', 'REEMBOLSO', 'AJUSTE') DEFAULT 'PAGO',
    METODO_PAGO 			ENUM('EFECTIVO', 'TARJETA_CREDITO', 'TARJETA_DEBITO', 'TRANSFERENCIA', 'YAPE', 'PLIN') NOT NULL,
    ESTADO_PAGO 			ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO', 'REEMBOLSADO') DEFAULT 'PENDIENTE',
    MONTO 					DECIMAL(10,2) NOT NULL,
    REFERENCIA_PAGO 		VARCHAR(100),
    FECHA_PAGO	 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT CHK_PAGO_MONTO CHECK (MONTO >= 0),
    CONSTRAINT FK_PAGO_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID)
) ENGINE=InnoDB;

CREATE TABLE ENVIO (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID 				INT NOT NULL,
    TRANSPORTISTA 			VARCHAR(100) NOT NULL,
    NUMERO_TRACKING	 		VARCHAR(100),
    COSTO_ENVIO 			DECIMAL(10,2) DEFAULT 0,
    FECHA_DESPACHO 			DATETIME NULL,
    FECHA_ENTREGA 			DATETIME NULL,
    
    CONSTRAINT CHK_ENVIO_COSTO CHECK (COSTO_ENVIO >= 0),
    CONSTRAINT FK_ENVIO_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID)
) ENGINE=InnoDB;

CREATE TABLE COMPROBANTE_FISCAL (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    PEDIDO_ID 				INT NOT NULL,
    TIPO_COMPROBANTE 		ENUM('BOLETA', 'FACTURA') NOT NULL,
    SERIE 					VARCHAR(10) NOT NULL,
    NUMERO 					VARCHAR(20) NOT NULL,
    MONTO_IMPUESTO 			DECIMAL(10,2) NOT NULL,
    MONTO_TOTAL 			DECIMAL(10,2) NOT NULL,
    FECHA_EMISION 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT UK_COMPROBANTE UNIQUE (SERIE, NUMERO),
    CONSTRAINT CHK_COMP_TOTAL CHECK (MONTO_TOTAL >= 0),
    CONSTRAINT FK_COMP_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID)
) ENGINE=InnoDB;

-- Modulo 6: Biblioteca Fisica
CREATE TABLE EJEMPLAR_BIBLIOTECA (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    LIBRO_ID 				INT NOT NULL,
    SUCURSAL_ID 			INT NOT NULL,
    CODIGO_BARRAS 			VARCHAR(50) NOT NULL UNIQUE,
    ESTADO_FISICO 			ENUM('NUEVO', 'BUENO', 'DETERIORADO', 'PARA_DESCARTE') DEFAULT 'BUENO',
    SITUACION 				ENUM('DISPONIBLE', 'PRESTADO', 'RESERVADO', 'LEYENDO_EN_SALA', 'EXTRAVIADO') DEFAULT 'DISPONIBLE',
    
    CONSTRAINT FK_EJEMPLAR_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID),
    CONSTRAINT FK_EJEMPLAR_SUCURSAL FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID)
) ENGINE=InnoDB;

CREATE TABLE PRESTAMO (
    ID 							INT AUTO_INCREMENT PRIMARY KEY,
    EJEMPLAR_ID 				INT NOT NULL,
    CLIENTE_ID 					INT NOT NULL,
    USUARIO_BIBLIOTECARIO_ID 	INT NOT NULL,
    TIPO_PRESTAMO 				ENUM('DOMICILIO', 'SALA') NOT NULL,
    FECHA_PRESTAMO 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_DEVOLUCION_ESPERADA	DATETIME NOT NULL,
    FECHA_DEVOLUCION_REAL 		DATETIME NULL,
    COSTO_ALQUILER 				DECIMAL(10,2) DEFAULT 0,
    ESTADO 						ENUM('EN_CURSO', 'DEVUELTO', 'RETRASADO', 'PERDIDO') DEFAULT 'EN_CURSO',
    
    CONSTRAINT CHK_PRESTAMO_COSTO CHECK (COSTO_ALQUILER >= 0),
    CONSTRAINT FK_PRESTAMO_EJEMPLAR FOREIGN KEY (EJEMPLAR_ID) REFERENCES EJEMPLAR_BIBLIOTECA(ID),
    CONSTRAINT FK_PRESTAMO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    CONSTRAINT FK_PRESTAMO_USUARIO FOREIGN KEY (USUARIO_BIBLIOTECARIO_ID) REFERENCES USUARIO(ID)
) ENGINE=InnoDB;

CREATE TABLE RENOVACION (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    PRESTAMO_ID 			INT NOT NULL,
    NUEVA_FECHA_DEVOLUCION 	DATETIME NOT NULL,
    FECHA_RENOVACION 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_RENOVACION_PRESTAMO FOREIGN KEY (PRESTAMO_ID) REFERENCES PRESTAMO(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PENALIZACION (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    PRESTAMO_ID 			INT NOT NULL,              -- UNIQUE REMOVIDO: Un préstamo puede recibir múltiples multas
    MOTIVO 					VARCHAR(255) NOT NULL,
    MONTO 					DECIMAL(10,2) NOT NULL,
    ESTADO 					ENUM('PENDIENTE', 'PAGADO', 'PERDONADO') DEFAULT 'PENDIENTE',
    
    CONSTRAINT CHK_PENALIZACION_MONTO CHECK (MONTO >= 0),
    CONSTRAINT FK_PENALIZACION_PRESTAMO FOREIGN KEY (PRESTAMO_ID) REFERENCES PRESTAMO(ID)
) ENGINE=InnoDB;

CREATE TABLE RESERVA_BIBLIOTECA (
    ID 						INT AUTO_INCREMENT PRIMARY KEY,
    LIBRO_ID 				INT NOT NULL,
    CLIENTE_ID 				INT NOT NULL,
    FECHA_SOLICITUD 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO 					ENUM('EN_ESPERA', 'NOTIFICADO', 'COMPLETADO', 'CANCELADO') DEFAULT 'EN_ESPERA',
    
    CONSTRAINT FK_RESBIB_LIBRO FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID),
    CONSTRAINT FK_RESBIB_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
) ENGINE=InnoDB;

-- =========================================================
-- DATA SET: INSERTS DE PRUEBA (DATA COHERENTE)
-- =========================================================
-- Seguridad
INSERT INTO ROL (NOMBRE, DESCRIPCION) VALUES 
('ADMINISTRADOR', 'CONTROL TOTAL'), ('VENDEDOR', 'GESTION DE VENTAS'), 
('BIBLIOTECARIO', 'GESTION DE PRESTAMOS'), ('ALMACENERO', 'GESTION DE INVENTARIO'), 
('CLIENTE_WEB', 'CLIENTE DEL PORTAL');

INSERT INTO USUARIO (NOMBRE_COMPLETO, EMAIL, PASSWORD_HASH) VALUES
('CARLOS MENDOZA', 'admin@tienda.com', 'HASH_ADMIN'),
('LAURA GOMEZ', 'ventas@tienda.com', 'HASH_VENDEDOR'),
('ANDRES RUIZ', 'biblioteca@tienda.com', 'HASH_BIBLIO'),
('PEDRO LOPEZ', 'almacen@tienda.com', 'HASH_ALMACEN'),
('JUAN PEREZ', 'juan@gmail.com', 'HASH_CLIENTE');

INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1,1), (2,2), (3,3), (4,4), (5,5);

-- Logística Inicial
INSERT INTO SUCURSAL (NOMBRE, DIRECCION, TELEFONO, TIENE_BIBLIOTECA) VALUES
('SEDE CENTRAL', 'AV LIMA 123', '999111222', TRUE),
('SUCURSAL NORTE', 'AV NORTE 456', '999333444', FALSE);

-- Catálogos de Libros
INSERT INTO CATEGORIA (NOMBRE) VALUES ('CIENCIA FICCION'), ('CIENCIA'), ('LITERATURA');
INSERT INTO EDITORIAL (NOMBRE, PAIS) VALUES ('DEBOLSILLO', 'ESPAÑA'), ('ALFAOMEGA', 'MEXICO');
INSERT INTO AUTOR (NOMBRE) VALUES ('FRANK HERBERT'), ('CARL SAGAN');

-- Libros con FORMATO, SLUG y metadatos web
INSERT INTO LIBRO (ISBN, TITULO, SLUG, IMAGEN_PORTADA, SINOPSIS, PAGINAS, FORMATO, PRECIO_VENTA_ACTUAL, PRECIO_ALQUILER_ACTUAL, EDITORIAL_ID) VALUES
('9788466361897', 'DUNE', 'dune-frank-herbert', '/img/libros/dune.jpg', 'Obra maestra de la ciencia ficción...', 700, 'TAPA_DURA', 120.00, 15.00, 1),
('9788401344497', 'COSMOS', 'cosmos-carl-sagan', '/img/libros/cosmos.jpg', 'Viaje por el universo...', 400, 'DE_BOLSILLO', 45.00, 8.00, 2);

INSERT INTO LIBRO_AUTOR (LIBRO_ID, AUTOR_ID) VALUES (1,1), (2,2);
INSERT INTO LIBRO_CATEGORIA (LIBRO_ID, CATEGORIA_ID) VALUES (1,1), (2,2);

-- B2C y B2B
INSERT INTO CLIENTE (USUARIO_ID, NOMBRE_RAZON_SOCIAL, TIPO_CLIENTE, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, EMAIL_CONTACTO, TELEFONO) VALUES
(5, 'JUAN PEREZ', 'INDIVIDUAL', 'DNI', '12345678', 'juan@gmail.com', '999888777'),
(NULL, 'UNIVERSIDAD NACIONAL', 'INSTITUCION', 'RUC', '20123456789', 'compras@universidad.edu.pe', '015554444');

INSERT INTO DIRECCION_ENVIO (CLIENTE_ID, ETIQUETA, DIRECCION_COMPLETA, CIUDAD, CODIGO_POSTAL) VALUES
(1, 'CASA', 'AV LOS PINOS 456', 'LIMA', '15001');

INSERT INTO INSTITUCION (CLIENTE_ID, TIPO_INSTITUCION, PERSONA_CONTACTO) VALUES
(2, 'UNIVERSIDAD', 'DR. LUIS REYES');

INSERT INTO CONTRATO (INSTITUCION_ID, CODIGO_CONTRATO, FECHA_INICIO, FECHA_FIN, DESCUENTO_PORCENTAJE) VALUES
(1, 'CON-UNI-2026', '2026-01-01', '2026-12-31', 15.00);

-- Reseñas y Cotizaciones
INSERT INTO RESENA_LIBRO (LIBRO_ID, CLIENTE_ID, CALIFICACION, COMENTARIO, APROBADO_MODERADOR) VALUES
(1, 1, 5, 'Increíble historia, el formato tapa dura es excelente.', TRUE);

INSERT INTO COTIZACION (INSTITUCION_ID, USUARIO_VENDEDOR_ID, ESTADO, TOTAL_ESTIMADO, FECHA_VALIDEZ) VALUES
(1, 2, 'ENVIADA', 1500.00, '2026-06-30 23:59:59');

-- Inventario de Tienda y KARDEX
INSERT INTO INVENTARIO_VENTA (SUCURSAL_ID, LIBRO_ID, CANTIDAD_DISPONIBLE, CANTIDAD_RESERVADA) VALUES
(1,1,100,5), (1,2,80,2);

INSERT INTO MOVIMIENTOS_INVENTARIO (USUARIO_ID, SUCURSAL_ID, LIBRO_ID, TIPO_MOVIMIENTO, TIPO_REFERENCIA, REFERENCIA_ID, CANTIDAD, DESCRIPCION) VALUES
(4, 1, 1, 'INGRESO_PROVEEDOR', 'AJUSTE', 1, 100, 'INGRESO INICIAL DUNE');

-- Carrito Web y Pedidos
INSERT INTO CARRITO (CLIENTE_ID) VALUES (1);
INSERT INTO CARRITO_DETALLE (CARRITO_ID, LIBRO_ID, CANTIDAD) VALUES (1,1,2);

INSERT INTO PEDIDO (CLIENTE_ID, SUCURSAL_ID, USUARIO_VENDEDOR_ID, DIRECCION_ENVIO_ID, CANAL_VENTA, TIPO_ENTREGA, ESTADO_ACTUAL, TOTAL) VALUES
(1, 1, 2, 1, 'ONLINE', 'DELIVERY', 'PAGADO', 240.00);

INSERT INTO DETALLE_PEDIDO (PEDIDO_ID, LIBRO_ID, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL) VALUES
(1, 1, 2, 120.00, 240.00);

INSERT INTO HISTORIAL_ESTADO_PEDIDO (PEDIDO_ID, USUARIO_ID, ESTADO, NOTAS) VALUES
(1, 2, 'PAGADO', 'PAGO CONFIRMADO');

INSERT INTO PAGO (PEDIDO_ID, TIPO_TRANSACCION, METODO_PAGO, ESTADO_PAGO, MONTO, REFERENCIA_PAGO) VALUES
(1, 'PAGO', 'YAPE', 'APROBADO', 240.00, 'OPERACION-999');

INSERT INTO ENVIO (PEDIDO_ID, TRANSPORTISTA, NUMERO_TRACKING, COSTO_ENVIO) VALUES
(1, 'OLVA COURIER', 'TRACK123456', 15.00);

INSERT INTO COMPROBANTE_FISCAL (PEDIDO_ID, TIPO_COMPROBANTE, SERIE, NUMERO, MONTO_IMPUESTO, MONTO_TOTAL) VALUES
(1, 'BOLETA', 'B001', '000001', 36.61, 240.00);

-- Biblioteca Operativa, Multas y Reservas
INSERT INTO EJEMPLAR_BIBLIOTECA (LIBRO_ID, SUCURSAL_ID, CODIGO_BARRAS, ESTADO_FISICO, SITUACION) VALUES
(1,1,'DUNE-001','NUEVO','DISPONIBLE'), 
(2,1,'COSMOS-001','DETERIORADO','PRESTADO');

INSERT INTO PRESTAMO (EJEMPLAR_ID, CLIENTE_ID, USUARIO_BIBLIOTECARIO_ID, TIPO_PRESTAMO, FECHA_DEVOLUCION_ESPERADA, COSTO_ALQUILER, ESTADO) VALUES
(2, 1, 3, 'DOMICILIO', '2026-06-30 18:00:00', 8.00, 'EN_CURSO');

INSERT INTO RENOVACION (PRESTAMO_ID, NUEVA_FECHA_DEVOLUCION) VALUES
(1, '2026-07-07 18:00:00');

-- Pruebas de multi-penalizaciones permitidas
INSERT INTO PENALIZACION (PRESTAMO_ID, MOTIVO, MONTO, ESTADO) VALUES
(1, 'RETRASO EN DEVOLUCION', 10.00, 'PENDIENTE'),
(1, 'DAÑO EXTRA EN HOJAS INTERNAS', 15.00, 'PENDIENTE');

INSERT INTO RESERVA_BIBLIOTECA (LIBRO_ID, CLIENTE_ID, ESTADO) VALUES
(2, 1, 'EN_ESPERA');