package com.biblioteca.app.modelo.enums;

public enum TipoMovimiento {
	INGRESO_PROVEEDOR, VENTA_FISICA, VENTA_ONLINE, DEVOLUCION, MERMA, TRASLADO_ENTRADA, TRASLADO_SALIDA, AJUSTE_MANUAL, DESCARTE_BIBLIOTECA
}
